### ISSUE TITLE
Direction = "top" purple squares glitch when partially in viewport

### ISSUE THREAD

**Issue by alexandrairwinliu** [dennismorello/react-awesome-reveal#10]
In Fade page of Demo, when Direction = "top" elements are partially in viewport, their opacity flashes between on and off

**Comment by dennismorello** [comment]
Hi,

This is a know issue. The quick workaround is to set the prop `triggerOnce` to `true`, but I am working on a fix.


Thank you!

**Comment by dennismorello** [comment]
Hi @alexandrairwinliu, version 1.6.5 fixes the issue.

Thanks!
