### ISSUE TITLE
Add when-prop in the vein of react-reveal

### ISSUE THREAD

**Issue by ljosberinn** [dennismorello/react-awesome-reveal#14]
Hi,

first, let me thank you for this modern alternative to `react-reveal`! Was mostly a plug- & play-replacement process.

However, one feature I'd like to see is missing: the [when](https://www.react-reveal.com/docs/when/) prop.

Example use case:
- login form shakes on error: `<Shake when={!!error}>{children}</Shake>`

**Comment by dennismorello** [comment]
Hi @ljosberinn,

stay tuned for future updates 🚀

**Comment by PeterKottas** [comment]
Bump on this.

**Comment by dennismorello** [comment]
Hi,

you can use the `reverse` prop as a temp workaround by binding it to a state variable of your component.

I have no plan to implement the `when` prop in the near future, but you can submit a PR if you would implement this in a performant way :)

**Comment by PeterKottas** [comment]
So let me see if I understand this. If you provide reverse={true}, it simply cancels/rewinds the already visible animation? I think it might be somewhat counterintuitive and the when props seem like a more straight forward solution. I personally don't need it, but it's reasonable to expect somebody who does to bring it on board. It's open-source after all ;)

**Comment by dennismorello** [comment]
This is out of scope.
