### ISSUE TITLE
ssr support

### ISSUE THREAD

**Issue by deantheiceman** [dennismorello/react-awesome-reveal#15]
Any support for ssr like react reveal?

**Comment by dennismorello** [comment]
Hi,

I have no plan to implement this feature in the near future, but feel free to submit PRs for this!

**Comment by bedjiken** [comment]
In the meantime the best workaround is to disable server side rendering and dynamically import the component on the client side.

For example in NextJS:

`import dynamic from "next/dynamic";

const NoSSRComponent = dynamic(
  () => import("NoSSRComponent"),
  {
    ssr: false
  }
);`

**Comment by remorses** [comment]
THe only thing i noticed is that when rendering in the server the Fade element has full opacity and in client side the element restarts the animation, setting the opacity to 0, making a "flash".

The preferred behaviour is to render the element with 0 opacity also in the server

**Comment by remorses** [comment]
I made a similar package that supports ssr and uses emotion for a smaller bundle size (do not need to import all animations css)

You can find it [here](https://github.com/remorses/baby-i-am-faded)

**Comment by dennismorello** [comment]
Version 3 featuring CSS-in-JS animations is now on beta, so I'm closing this since the library should now work properly with SSR.

**Comment by mstojanovic8** [comment]
> Version 3 featuring CSS-in-JS animations is now on beta, so I'm closing this since the library should now work properly with SSR.

Hi, can you explain how this solves the following issue:

> THe only thing i noticed is that when rendering in the server the Fade element has full opacity and in client side the element restarts the animation, setting the opacity to 0, making a "flash".
>
> The preferred behaviour is to render the element with 0 opacity also in the server

Im using latest version (v4.2.5) and when rendered on server, divs has `opacity: 0` and they are not visible.

Sorry for commenting on a long time ago closed issue.

Thanks in advance.
