### ISSUE TITLE
Markup for 'ul' disappears 

### ISSUE THREAD

**Issue by fobossalmeron** [dennismorello/react-awesome-reveal#16]
When applied to lists, the `<ul></ul>` tags disappear, is this intentional?  
It's my understanding that this is not valid html markup.

Pd. Congrats on making this library! :) It's a pleasure to upgrade from react-reveal.

**Comment by dennismorello** [comment]
Hi @fobossalmeron,

first of all thank you for using react-awesome-reveal!

I will have a look at the issue you discovered, a fix will be released soon :)

**Comment by dennismorello** [comment]
Version [2.3.1](https://www.npmjs.com/package/react-awesome-reveal/v/2.3.1) fixes this issue!
