### ISSUE TITLE
Specific imports

### ISSUE THREAD

**Issue by PeterKottas** [dennismorello/react-awesome-reveal#17]
It would be great if it was possible to import specific components instead of the whole bundle. Something along the lines of
```javascript
import {Fade} from 'react-awesome-reveal/Fade'.
```
The lib is fairly small (gj on that) but this would make it even smaller. 
It's fairly easy to do, I am doing something similar in some of my libs, just set up an extra build step that builds all files with babel and puts them in a specific folder.

You can check out my build script for reference: [GuestBell forms transpile](https://github.com/PeterKottas/guestbell-forms/blob/master/package.json#L81)

**Comment by dennismorello** [comment]
Hi @PeterKottas,

I don't think this would make your final bundle significantly smaller since

1. `react-awesome-reveal` is already very tiny
2. all the effects are internally wrapping the `Reveal` component – they just pass to it a different `animation` prop

Thank you for your idea btw!

**Comment by PeterKottas** [comment]
Should have looked at the code you are right, it seemed reasonable at the time of writing. Cheers

**Comment by itayganor** [comment]
![image](https://user-images.githubusercontent.com/6430313/103143378-72c3f280-471d-11eb-8b39-1631a2f6280f.png)

@dennismorello Isn't `32.3 KB` big? I only import `{Fade}` throughout my application
