### ISSUE TITLE
Nested cascade

### ISSUE THREAD

**Issue by PeterKottas** [dennismorello/react-awesome-reveal#18]
I was curious if you thought about this. How would one achieve e.g. combined Slide and Fade, both in cascade mode? This seems like a fairly standard animation (appear one by one sliding from the left) but I am afraid that doesn't work atm. I understand that this is a sideproduct of the design. It merely loops over children and wraps them in an animation component with delay. Maybe an API could be introduced. I can picture something like "nested animations" where you would simply provide an array of animation components from the lib. There would then be used for "extra" wrapping while looping over the children. Just thinking out loud here :)

**Comment by dennismorello** [comment]
Hi @PeterKottas,

it sounds like something you can already do by combining different effects and playing with the `delay` prop.

If this is enough I would not add levels of complexity to `react-awesome-reveal`, I would keep it simple ;)

**Comment by PeterKottas** [comment]
I sort of agree, but still think it might be a tempting feature. You can do it by manually looping over children in your code. Needless to say, not a very user-friendly way of doing things. I am thinking this could be implemented as an extra component (or maybe as part of a new lib with dependency on this). I can imagine something like this.

```typescript
import { AdvancedReveal } from 'react-awesome-reveal';

const MyComponent = () => {
  return <Reveal animation={['fade', 'slide']}>{/* Content here */}</Reveal>;
};
```
That would simply chain the reveals. This could easily work with cascade as well. Maybe it would make sense to keep this open as a "help-wanted" issue? See if others might be interested in such functionality.

**Comment by PeterKottas** [comment]
It would require fairly minimal code, just some extra loop here https://github.com/dennismorello/react-awesome-reveal/blob/master/src/Reveal.tsx#L37

**Comment by bozskejkaja** [comment]
Hey, I'm not sure if anyone's still looking for how to do this, but I found out that when I use `Fade` and provide a `direction` prop, the animation does indeed combine a Slide and a Fade.
```
 <Fade cascade damping={0.1} triggerOnce direction={"right"}>
...
</Fade>
```
![Slide_Fade](https://user-images.githubusercontent.com/19172849/85542657-96e13280-b619-11ea-8943-da917c217b1f.gif)

**Comment by dennismorello** [comment]
> Hey, I'm not sure if anyone's still looking for how to do this, but I found out that when I use `Fade` and provide a `direction` prop, the animation does indeed combine a Slide and a Fade.
> 
> ```
>  <Fade cascade damping={0.1} triggerOnce direction={"right"}>
> ...
> </Fade>
> ```
> 
> ![Slide_Fade](https://user-images.githubusercontent.com/19172849/85542657-96e13280-b619-11ea-8943-da917c217b1f.gif)

This is how the `Fade` animation with a direction is intended to work. You can use the `Slide` animation if you do not want the fade effect.
