### ISSUE TITLE
Generic component

### ISSUE THREAD

**Issue by PeterKottas** [dennismorello/react-awesome-reveal#19]
It would be great if, on top of importing different components, there would be one top-level component where you could provide "type" prop and it would render specific effect for you. Useful for wrapped components where you want to override effect for consistent behavior across an app.

**Comment by dennismorello** [comment]
Hi @PeterKottas, please upgrade to version 2.4.1 and follow the instructions reported [here](https://github.com/dennismorello/react-awesome-reveal#generic-animations).

**Comment by PeterKottas** [comment]
Lovely, thanks!
