### ISSUE TITLE
Elements are visible if fractions prop is used

### ISSUE THREAD

**Issue by boroma4** [dennismorello/react-awesome-reveal#24]
Hi, first of all for great work with the library! 
I have been using it in my project and when I have tried to use fraction, components are visible before required fraction is reached. When fraction is 0, components are initially invisible and behave as expected.

![image](https://user-images.githubusercontent.com/52993491/80757342-af166300-8b3c-11ea-9e44-4bb2dc89bb3f.png)
Items has fraction set to 0.5. Second element is partially visible but < 0.5 fraction. When 0.5 is reached, animation is triggered anyway ( moving from invisible to the same place).

**Comment by dennismorello** [comment]
Hi @boroma4, can you please attach a snippet of the involved code? The `fraction` option is passed down to the Intersection Observer constructor, I don’t think it is an issue with the library.

Thanks!

**Comment by boroma4** [comment]
I dont have it anymore unfortunately, I was just trying how it works at that time. I believe it was just image and text inside of a <Fade triggerOnce fraction ={0.5}>. I know it is not very useful info, sorry for that.

**Comment by dennismorello** [comment]
OK, I am closing this then!
