### ISSUE TITLE
Problem with react-router Link and delay with cascade

### ISSUE THREAD

**Issue by mattyusdev** [dennismorello/react-awesome-reveal#25]
Hi, 

First thank you for the library! great work!
It was excaclty what I've been looking for :)

#1
I've got an issue when browsing through pages with react-router "Link", for example, I'm using Fade, and the components should not be visible at the beggining but when moving into another page for a split seconds they are shown and then the animation starts.

I've managed to solve it by adding "opacity: 0" to it's all children and another fade animation to wrap them and get it back to "opacity: 1".

#2 
It seems like when 'cascade' is active, 'delay' won't work.

Maybe i'm doing something wrong? any way hope you'll get look into that :)

**Comment by dennismorello** [comment]
Hi @mattyusdev,

this could be related to #26, so after having fixed that I will take a look at this.


Cheers

**Comment by dennismorello** [comment]
I'm closing this with the release of version 3 beta.
