### ISSUE TITLE
Support for ForwardRef

### ISSUE THREAD

**Issue by itayganor** [dennismorello/react-awesome-reveal#26]
Hi Dennis,
First of all, I wanted to say your library is amazing! 🌟 

I do have one suggestion tho:

When you use a Reveal component on a custom component, it won't work. You need to wrap it with a "vanilla" HTML element like div, span, etc. This is caused because components do not pass references to their container element by default.

But, since React has `forwardRef`, this is actually possible to solve.

I used [@tippyjs/react](https://github.com/atomiks/tippyjs-react) which [seems to support `forwardRef`](https://github.com/atomiks/tippyjs-react#component-children). I guess it's not that of a change (correct me if I'm wrong).

Anyway, until this issue is not solved, it might be a good idea to consider recalculate `cascade` when custom components are part of the chain. The cascade animation won't work (because what I described above) but it will get into the delay calculation. I think it'll be better to exclude it from the delay (so following elements won't be too much delayed).

xoxo

**Comment by dennismorello** [comment]
Hi Itay,

thank you for having written this issue so well! I will investigate and fix this unexpected behavior during the weekend, and a new release will be released soon.


Cheers

**Comment by dennismorello** [comment]
After reading [this](https://reactjs.org/docs/forwarding-refs.html#note-for-component-library-maintainers), I prefer not to handle refs internally and let the user take care of them. I think wrapping your custom components with a `<div>` is a reasonable trade-off.

**Comment by itayganor** [comment]
Seems legit, but adding extra elements with no benefit rather than a compromised workaround is not a good practice. It means there's another div to be taken care of, in terms of CSS and layout, Adds complexity to an already complicated element tree, and just another "gotcha" for the library to warn about. 

If you ask me, it sounds like a great reason to have a major bump.
