### ISSUE TITLE
Animate css in the bundle

### ISSUE THREAD

**Issue by PeterKottas** [dennismorello/react-awesome-reveal#27]
The entire animate.css is included as a string in the package, consequently making the library unnecessarily large. After reading [this](https://github.com/dennismorello/react-awesome-reveal/issues/8), I kind of understand why this was done, but this is quite a disaster for ssr and statically generated pages. My generated HTML pages grew by 50% after adding this lib because the style is inline loaded (yet the same code also remains in the js that needs to be downloaded subsequently). I think it would make sense to make this optional. Including this directly in the source is not a good idea IMHO. I for one would prefer if I could take care of this on my end, maybe even pick only the parts of animate.css that I am interested in.

**Comment by dennismorello** [comment]
Hi @PeterKottas,

I agree with you. I am going to release a new major version with a per-component CSS handling, so to minimize the amount of styling rules included in the final bundle.

**Comment by PeterKottas** [comment]
Lovely! Looking forward to that, glhf! :)

**Comment by dennismorello** [comment]
Version 3 featuring CSS-in-JS animations is now on beta, so I'm closing this.
