### ISSUE TITLE
Content flickering

### ISSUE THREAD

**Issue by Frostbourn** [dennismorello/react-awesome-reveal#30]
Thank you for the awesome work! I love it.

Can you tell me how can I prevent to reload content before animation? Content loads -> then animation triggers. This creates not looking good flicker of content. Do you have any solution for that?

**Comment by dennismorello** [comment]
Hi @Frostbourn, the quick fix is to use version 2.4.0 of the library (which initially sets “display: hidden” to the child element), I will release a new version that lets you choose wether to initially hide elements or not by setting a prop.

**Comment by Frostbourn** [comment]
Great, I can't wait!

**Comment by dennismorello** [comment]
Version 3 with a fix for this is now on beta, I'm closing this.
