### ISSUE TITLE
animations not working - react-awesome-reveal

### ISSUE THREAD

**Issue by a2441918** [dennismorello/react-awesome-reveal#35]
I want to use react-awesome-reveal in my typescript project but the animations doesnt seem to work. However, it works when I use react-reveal. Please advice on what I am missing.

    import React, { Component } from "react";
    import { render } from "react-dom";
    import Hello from "./Hello";
    import { Fade } from "react-awesome-reveal";
    import ReactRevealFade from "react-reveal/Fade";
    import "./style.css";

    class App extends Component {
      constructor() {
        super();
        this.state = {
          name: "React"
        };
      }

      render() {
        return (
          <div>
            <Fade>
              <Hello name={this.state.name} />
            </Fade>
            <ReactRevealFade left>
              <Hello name={this.state.name} />
            </ReactRevealFade>
            <p>Start editing to see some magic happen :)</p>
          </div>
        );
      }
    }

    render(<App />, document.getElementById("root"));

Stackblitz Code: [Link][1]

Any help is appreciated.

  [1]: https://stackblitz.com/edit/react-tvsxrt

**Comment by dennismorello** [comment]
Hi @a2441918,

unfortunately the animations work only if a built-in element is passed as a direct child. The quick workaround is to wrap your component inside a `<div>`.

**Comment by a2441918** [comment]
@dennismorello Thanks.

**Comment by dennismorello** [comment]
Use the version 3.0.0-beta.0 to benefit from many enhancements, a stable v3 release will be released soon!
