### ISSUE TITLE
HeadShake removed

### ISSUE THREAD

**Issue by a2441918** [dennismorello/react-awesome-reveal#37]
Hi, I am using HeadShake in my code. Any reason for removing it in v3? I still see it in the demo though.

**Comment by a2441918** [comment]
Got it. Using <AttensionSeeker effect='headShake'>{child}</AttensionSeeker>

**Comment by coltenkrauter** [comment]
That is odd.. Why was headshake removed? It is still in the demo... @dennismorello?

**Comment by dennismorello** [comment]
> ```ts
> 
> import { HeadShake } from 'react-awesome-reveal';
> 
> // Results in: Attempted import error: 'HeadShake' is not exported from 'react-awesome-reveal'
> 
> ```
> 
> That is odd.. Why was headshake removed? It is still in the demo... @dennismorello?

This has not been removed:

<AttensionSeeker effect='headShake'>{child}</AttensionSeeker>

**Comment by dennismorello** [comment]
> ```ts
> 
> import { HeadShake } from 'react-awesome-reveal';
> 
> // Results in: Attempted import error: 'HeadShake' is not exported from 'react-awesome-reveal'
> 
> ```
> 
> That is odd.. Why was headshake removed? It is still in the demo... @dennismorello?

This has not been removed:

```jsx
<AttensionSeeker effect='headShake'>{child}</AttensionSeeker>

```

**Comment by coltenkrauter** [comment]
Sorry -- didn't mean to jump the gun there. 

So, now I am getting,

```ts
import { AttensionSeeker } from 'react-awesome-reveal';
// Results in: Attempted import error: 'AttensionSeeker' is not exported from 'react-awesome-reveal'.
```

Am I doing this wrong? 

Also, why is it that I can't simply import HeadShake?

**Comment by coltenkrauter** [comment]
🤦

**Comment by coltenkrauter** [comment]
AttensionSeeker => AttentionSeeker

**Comment by dennismorello** [comment]
> Also, why is it that I can't simply import HeadShake?

Because I grouped all effects that grab the user attention.

**Comment by coltenkrauter** [comment]
Ah, that makes sense. Seems like a good decision. Thanks for clarifying. I saw that in the README but it hadn't clicked...
