### ISSUE TITLE
Skip animations above the scroll position after user refresh the page.

### ISSUE THREAD

**Issue by dizip** [dennismorello/react-awesome-reveal#39]
Hi guys, 
Is there any option to skip animations above the scroll position when the user refreshes the page in the middle of its height?

Thanks in advance!

**Comment by dennismorello** [comment]
Hi @dizip, this would require storing the scroll position somewhere resistant to page refreshes (eg. `localStorage`) and implementing the logic needed to handle your use case. I don't see any benefit on implementing such a thing directly inside the library, can you tell me more about your use case?
