### ISSUE TITLE
className prop in version 3.x

### ISSUE THREAD

**Issue by kaliwa** [dennismorello/react-awesome-reveal#40]
I expect the className prop to come back, because I have a hard time wrapping the elements; row for example.

**Comment by dennismorello** [comment]
Hi @kaliwa, I will add `className` and `style` support. Do you expect them to have effect on the container element added by the library or on the child element you pass?

**Comment by kaliwa** [comment]
Thank you for responding, I hope the effect will be on the child element.

**Comment by dennismorello** [comment]
Fixed in [v3.1.0](https://www.npmjs.com/package/react-awesome-reveal/v/3.1.0). Thank you!
