### ISSUE TITLE
Some elements with wrapped animation components are losing classes

### ISSUE THREAD

**Issue by endrits079** [dennismorello/react-awesome-reveal#45]
I have an element with the class container and it has 2 children one with class left and one right
I wrapped children with classes left and right with different animation components tried (Fade,Slide,Bounce,Flip) and the styling was messed  up when I check on developers tools the elements are missing the classes but the inner children have their classes

**Comment by dennismorello** [comment]
Hi, can you please share a code snippet?

**Comment by endrits079** [comment]
https://gist.github.com/endrits079/cc5f5378bb825ba92a75516eb2b82244 
the div with class left and right are getting their  classes removed

**Comment by endrits079** [comment]
![image](https://user-images.githubusercontent.com/27869578/92961176-1e974a00-f46f-11ea-8294-f584ccb74a9d.png)
The rounded div is supposed to have the class left but doesn't have any

**Comment by endrits079** [comment]
Giving the same class to the animation element seems to solve the issue, even the class still missing on the div the correct styles are applied

**Comment by dennismorello** [comment]
Please use the **className** prop to add classes to the container element and the **childClassName** prop to add class to the child element wrapped by the animated component. Refer to the documentation to see the details!

**Comment by dennismorello** [comment]
**UPDATE**

Version 3.3.1 includes a fix that allows children to keep their className and style props (they are merged with the ones passed to childClassName and childStyle of an animated component).
