### ISSUE TITLE
Performance is worse with multiple animation  

### ISSUE THREAD

**Issue by rizkyramadhan** [dennismorello/react-awesome-reveal#48]
Coming from react-reveal, and I am noticing that react-awesome-reveal animation is jittery and scrolling is janky when there are multiple animation played. Esepecially in animation heavy landing page.

Sorry but I can't create codesandbox at the moment, will do when I have the time. For now, I just informing my experience...

**Comment by dennismorello** [comment]
This looks strange... Which browser and hardware are you using?

**Comment by dennismorello** [comment]
I'm closing this because I cannot reproduce.
