### ISSUE TITLE
The Internet Explorer problem...

### ISSUE THREAD

**Issue by mploux** [dennismorello/react-awesome-reveal#51]
Hello,
First thanks a lot for this package, it's awesome !

I am working on a website for a client, the problem is it's in a sector where a lot of people still run internet explorer on XP...
Very annoying to dev a modern website and make it work properly on every browser. Turns out IE is not dead for some people x)

I am having this error on IE11:
`'IntersectionObserver' is undefined`

I'm sure it's because something is not compatible with IE but it would be great if the main Reveal component would just not render in case the browser is IE. We wouldn't have animations anymore but if IE users want them they can update there browser.

Do you feel like it's something worth working on ? 
If you have a workaround I'm interested !

**Comment by dennismorello** [comment]
Hi @mploux,

if you have to support older browsers like IE11 you need a polyfill for the IntersectionObserver API (pick [this one](https://www.npmjs.com/package/intersection-observer)).


Hope it helps!

**Comment by dennismorello** [comment]
Follow [this](https://www.npmjs.com/package/react-intersection-observer#polyfill) basic guide to conditionally load the IntersectionObserver polyfill.
