### ISSUE TITLE
Children elements split up

### ISSUE THREAD

**Issue by itayganor** [dennismorello/react-awesome-reveal#52]
Hi there :)

Consider the following snippet:

```jsx
<Fade className="hello">
    <span>hi</span>
    <span>there</span>
</Fade>
```

In 2.4.2, both spans were rendered inside `.hello`.

Now, on 3.3.1, `Fade` breaks this down into two divs, each containing a single span.

![image](https://user-images.githubusercontent.com/6430313/97812608-07185880-1c8b-11eb-9444-34a5761c4a5f.png)

Codesandbox: https://codesandbox.io/s/react-awesome-reveal-v3-breaks-children-irxig?file=/src/App.js

Why does this happen?
It was quite handy I could supply `Fade` a className instead of wrapping its children with yet another `div`.

Thanks!

**Comment by dennismorello** [comment]
Hi @itayganor,

just wrap your 2 spans inside a React fragment:

```jsx
<Fade className="hello">
  <React.Fragment>
      <span>hi</span>
      <span>there</span>
  </React.Fragment>
</Fade>
```

**Comment by hedwardd** [comment]
@morellodev 

First, thank you for this awesome library. I'm very grateful.

Second, I had the same issue as above and was confused until finding this issue. (Unless I missed it) Might I suggest adding something to the documentation about this effect? Maybe something similar to [this](https://www.npmjs.com/package/react-reveal#children)

Again, thank you for the work you've put into making this library. It's much appreciated.

**Comment by itayganor** [comment]
Maybe Typescript can help protecting this, with an expectation to get a single `ReactElement` and not `ReactElement[]` or `ReactNode`. 

If not, maybe a log message in the console when the component gets more than a single child.
