### ISSUE TITLE
How to trigger animation on variable change?

### ISSUE THREAD

**Issue by MihaiWill** [dennismorello/react-awesome-reveal#53]
What is the equivalent of `spy` prop from [`react-reveal`](https://www.react-reveal.com/docs/props/)
```
spy: Any change in this prop value will cause the element to be revealed again. It makes sense to set it to some state variable. Disables the initial reveal animation (use appear prop to reenable it). Optional.
```

**Comment by dennismorello** [comment]
This is currently not supported by this library, it is not a replacement for react-reveal.

This library focuses on efficiently animating elements when they enter the viewport.

**Comment by coltenkrauter** [comment]
@dennismorello I really like what you have done here. Do you have any plans for adding support for this in the future?

**Comment by coltenkrauter** [comment]
Also, @MihaiWill, you might be able to use the reverse prop to get the results that you require. [Helpful comment in #14](https://github.com/dennismorello/react-awesome-reveal/issues/14#issuecomment-578487979)
