### ISSUE TITLE
Programmatically trigger reveal or disable capability

### ISSUE THREAD

**Issue by TheMeteoRain** [dennismorello/react-awesome-reveal#55]
Hi,

just here to leave a suggestion to allow programatically trigger reveal or disable them on the fly. 

For example:
You have a one big web page and you have headings that include anchor links (e.g. /#about), so you can jump between sections quickly. If I implement this now and jump to third heading on the site, sections one and two still hasn't triggered their reveal animations, but when I scroll up, they will trigger. The reveals don't look that great when scrolling top of the page, because they were implemented scrolling to bottom of the page "in-mind".

**Comment by imnasnainaec** [comment]
Without more control on triggering events, `react-awesome-reveal` is not a sufficient [substitute](https://github.com/rnosov/react-reveal/issues/105#issuecomment-703000289) for `react-reveal`.

**Comment by dennismorello** [comment]
@imnasnainaec no-one said this is a replacement for `react-reveal` 🤔

**Comment by dennismorello** [comment]
The main purpose of `react-awesome-reveal` is clearly written at the beginning of the README:

> React Awesome Reveal is a library for React apps written in TypeScript that adds reveal animations using the Intersection Observer API to detect when the elements appear in the viewport. Animations are internally provided by Emotion and implemented as CSS Animations to benefit from hardware acceleration.
