### ISSUE TITLE
Map Fade's items at same time in viewport.

### ISSUE THREAD

**Issue by ivanjeremic** [dennismorello/react-awesome-reveal#61]
I have a map which maps over some data and returns the component which is wrapped by the Fade, my problem now is the first 3 items are getting faded in from left at the same tim instead of one by one, this only happens on the 3 that fit in the viewport of my monitor all other components below work fine and fade in one by one, so is it possible to actually do this? I tried a few props and read the docs but nothing seems to fix this. 

Thanks

**Comment by dennismorello** [comment]
Hi @ivanjeremic, can you attach the code snippet?

**Comment by ivanjeremic** [comment]
> Hi @ivanjeremic, can you attach the code snippet?

Sure here the map par with the code.
`{data &&
        data.length &&
        data.map((post, index) => (
          <Fade direction="bottom-left" triggerOnce={true} cascade={true}>
            <Fragment key={post.id}>
              <NewsComponent post={post} />
            </Fragment>
          </Fade>
        ))}`

**Comment by dennismorello** [comment]
I would refactor your code to

```jsx
{
  data && data.length && (
    <Fade direction="bottom-left" triggerOnce cascade>
      {data.map((post, index) => (
        <NewsComponent key={post.id} post={post} />
      ))}
    </Fade>
  );
}
```

Let me know if it helps!

**Comment by ivanjeremic** [comment]
> I would refactor your code to
> 
> ```js-jsx
> {
>   data && data.length && (
>     <Fade direction="bottom-left" triggerOnce cascade>
>       {data.map((post) => (
>         <NewsComponent key={post.id} post={post} />
>       ))}
>     </Fade>
>   );
> }
> ```
> 
> Let me know if it helps!

Thanks this helped to solve the issue. One more question regarding map I have is it possible that every child fade's in from a different direction? `left right left right...`

**Comment by dennismorello** [comment]
Glad it helped!

For the second question, you should wrap the *i*-th child with a `<Fade>` component, passing it the `direction` prop of your choice (it could be simply a circular selection over an array of directions).
