### ISSUE TITLE
react-reveal props I miss: spy and appear

### ISSUE THREAD

**Issue by andrepadeti** [dennismorello/react-awesome-reveal#65]
Is this repo a fork of react-reveal? I'd love to use this more modern version but my use case makes use of two props I haven't been able to find here: `spy` and `appear`. Is there a workaround?

**Comment by dennismorello** [comment]
Hi, this is not a fork of react-reveal, this is a completely new and different implementation

**Comment by andrepadeti** [comment]
That's okay. I thought it might be a fork because of [this comment](https://github.com/rnosov/react-reveal/issues/106#issuecomment-703000171).
If I could just put in my two pennies worth, it would be nice if that could be implemented :-)
Keep up the good work!

**Comment by dennismorello** [comment]
Thank you @andrepadeti, feel free to submit a PR!

Merry Christmas 🎄
