### ISSUE TITLE
Detecting changes after a route change?

### ISSUE THREAD

**Issue by albertcarrete** [dennismorello/react-awesome-reveal#66]
I'm wondering if this is within the scope of the package. Currently, react-awesome-reveal uses Intersection Observer to determine if an element is within the viewport. So when an element remains within the viewport during say, a route change that uses the same component, RAR does nothing because the element hasn't left the viewport. I would like a way to reanimate the same initial animation each time the route changes. Would this issue be within the scope of RAR?

I've attached a sandbox for demonstration purposes:
[https://codesandbox.io/s/musing-mclaren-xtuhf?file=/src/DynamicPage.js](https://codesandbox.io/s/musing-mclaren-xtuhf?file=/src/DynamicPage.js)

**Comment by dennismorello** [comment]
This is out of scope. Use another solution to add transitions on route changes (see https://reactrouter.com/web/example/animated-transitions).
