### ISSUE TITLE
Unexpected animation over nested lists

### ISSUE THREAD

**Issue by caseymhunt** [dennismorello/react-awesome-reveal#67]
### Observed behavior
Currently when nested lists are present, the library will animate over the list items and treat the nested list as a single object rather than iterating over the list items within the nested list when the `cascade` prop is in use. 

Simplified example code:
```js
<ul>
   <Fade cascade>
      <li>list item</li>
      <li>list item</li>
      <li>
         <ul>
            <li>sub-item</li>
            <li>sub-item</li>
         </ul>
      </li>
      <li>list item</li>
   </Fade>
</ul>
```

### Expected behavior
I expect that all children (and grand-children) wrapped within `<Fade>` will animate in sequence in the cascade. Instead, (in the example above) the sub-items appear all together instead of individually.

**Comment by dennismorello** [comment]
You have to wrap the entire <ul> inside the <Fade> component.

Dennis Morello
Front-End Engineer

W: https://morello.dev
E: dennismorello@gmail.com
Il 1 feb 2021, 22:27 +0100, Casey Hunt <notifications@github.com>, ha scritto:

**Comment by caseymhunt** [comment]
When I wrap the entire `<ul>` and remove the `cascade` prop the whole list comes in as a single chunk.

**Comment by caseymhunt** [comment]
This appears to be related- I am using a `Box` primitive component (Read: https://theme-ui.com/components/box/) and when I use this component along with the `as` prop, the animation behavior I see is different than if I use raw HTML (`ul`). 

My code looks more like this:
```js
<Fade>
   <Box as="ul">
      <Box as="li">...</Box>
      ...
   </Box>
</Fade>
```

**Comment by dennismorello** [comment]
It is not an issue with `react-awesome-reveal`, it is a matter of components composition. Since the lib uses the element type to detect lists (`ol`s and `ul`s), you should use a snippet like this to achieve the desired result:

```js
const AnimatedList = () => (
  <Box as="ul">
    <Fade cascade>
      <Box as="li">Milk</Box>
      <Box as="li">Eggs</Box>
      <Box as="li">Sugar</Box>
    </Fade>
  </Box>
);
```
